//
//  File.swift
//  
//
//  Created by Secret Asian Man Dev on 22/8/21.
//

import Foundation

/// Represents one line in a larger multi lined document.
/// Generated by method `enumerateSubstrings`.
/// Docs: https://developer.apple.com/documentation/foundation/nsstring/1416774-enumeratesubstrings
internal struct Line {
    let string: String
    let substringNsRange: NSRange
    let enclosingNsRange: NSRange
}

extension Line : Equatable {
    /// Compare strings by their contents only, not their ranges.
    static func ==(lhs: Self, rhs: Self) -> Bool {
        /// Compares:
        /// - string contents
        /// - newline length
        /// - Warning: does not compare newline contents!
        (lhs.string == rhs.string) && (lhs.enclosingNsRange.length == rhs.enclosingNsRange.length)
    }
}
